module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'test',
        'chore',
        'ci',
        'perf',
        'revert',
        'security',
        'build',
      ],
    ],
    'subject-case': [2, 'never', ['start-case', 'pascal-case', 'upper-case']],
    'header-max-length': [2, 'always', 100],
    'scope-enum': [
      1,
      'always',
      [
        'core',
        'adapters',
        'registry',
        'ws',
        'client',
        'cli',
        'testing',
        'grpc',
        'mcp-bridge',
        'codex-bridge',
        'create-a2a-agent',
        'demo',
        'registry-ui',
        'docs',
        'deps',
        'release',
        'ci',
      ],
    ],
  },
};
