apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: a2a-mesh
  namespace: '{{ .Values.namespace }}'
spec:
  selector:
    matchLabels:
      app: a2a-mesh
  endpoints:
    - port: http
      path: /health
